#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: da8b975
#
Name     : R-sm
Version  : 2.2.6.0
Release  : 52
URL      : https://cran.r-project.org/src/contrib/sm_2.2-6.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/sm_2.2-6.0.tar.gz
Summary  : Smoothing Methods for Nonparametric Regression and Density
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-sm-lib = %{version}-%{release}
Requires: R-sm-license = %{version}-%{release}
Requires: tcl
Requires: tk
BuildRequires : buildreq-R
BuildRequires : tcl-dev
BuildRequires : tk-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
'Applied Smoothing Techniques for Data Analysis -
  The Kernel Approach with S-Plus Illustrations' Oxford University Press.

%package lib
Summary: lib components for the R-sm package.
Group: Libraries
Requires: R-sm-license = %{version}-%{release}

%description lib
lib components for the R-sm package.


%package license
Summary: license components for the R-sm package.
Group: Default

%description license
license components for the R-sm package.


%prep
%setup -q -n sm
pushd ..
cp -a sm buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1708277756

%install
export SOURCE_DATE_EPOCH=1708277756
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-sm
cp %{_builddir}/sm/inst/COPYING %{buildroot}/usr/share/package-licenses/R-sm/17e3b0eea99abffe6ac71e65627413236e0b117a || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sm/CITATION
/usr/lib64/R/library/sm/COPYING
/usr/lib64/R/library/sm/DESCRIPTION
/usr/lib64/R/library/sm/INDEX
/usr/lib64/R/library/sm/Meta/Rd.rds
/usr/lib64/R/library/sm/Meta/data.rds
/usr/lib64/R/library/sm/Meta/features.rds
/usr/lib64/R/library/sm/Meta/hsearch.rds
/usr/lib64/R/library/sm/Meta/links.rds
/usr/lib64/R/library/sm/Meta/nsInfo.rds
/usr/lib64/R/library/sm/Meta/package.rds
/usr/lib64/R/library/sm/NAMESPACE
/usr/lib64/R/library/sm/NEWS.md
/usr/lib64/R/library/sm/R/sm
/usr/lib64/R/library/sm/R/sm.rdb
/usr/lib64/R/library/sm/R/sm.rdx
/usr/lib64/R/library/sm/data/Rdata.rdb
/usr/lib64/R/library/sm/data/Rdata.rds
/usr/lib64/R/library/sm/data/Rdata.rdx
/usr/lib64/R/library/sm/help/AnIndex
/usr/lib64/R/library/sm/help/aliases.rds
/usr/lib64/R/library/sm/help/paths.rds
/usr/lib64/R/library/sm/help/sm.rdb
/usr/lib64/R/library/sm/help/sm.rdx
/usr/lib64/R/library/sm/history.txt
/usr/lib64/R/library/sm/html/00Index.html
/usr/lib64/R/library/sm/html/R.css
/usr/lib64/R/library/sm/scripts/air_band.q
/usr/lib64/R/library/sm/scripts/air_boot.q
/usr/lib64/R/library/sm/scripts/air_cont.q
/usr/lib64/R/library/sm/scripts/air_dens.q
/usr/lib64/R/library/sm/scripts/air_hcv.q
/usr/lib64/R/library/sm/scripts/air_imag.q
/usr/lib64/R/library/sm/scripts/air_ind.q
/usr/lib64/R/library/sm/scripts/air_inds.q
/usr/lib64/R/library/sm/scripts/air_scat.q
/usr/lib64/R/library/sm/scripts/bin_use.q
/usr/lib64/R/library/sm/scripts/birth1.q
/usr/lib64/R/library/sm/scripts/birth2.q
/usr/lib64/R/library/sm/scripts/bissell1.q
/usr/lib64/R/library/sm/scripts/bissell2.q
/usr/lib64/R/library/sm/scripts/bissell3.q
/usr/lib64/R/library/sm/scripts/citrate.q
/usr/lib64/R/library/sm/scripts/dogs.q
/usr/lib64/R/library/sm/scripts/edfgrad.q
/usr/lib64/R/library/sm/scripts/follicle.q
/usr/lib64/R/library/sm/scripts/geys3d.q
/usr/lib64/R/library/sm/scripts/geys_ts.q
/usr/lib64/R/library/sm/scripts/index.doc
/usr/lib64/R/library/sm/scripts/lc_comp.q
/usr/lib64/R/library/sm/scripts/lc_dens.q
/usr/lib64/R/library/sm/scripts/lc_rr.q
/usr/lib64/R/library/sm/scripts/lynx.q
/usr/lib64/R/library/sm/scripts/mackgam.q
/usr/lib64/R/library/sm/scripts/mackmap.q
/usr/lib64/R/library/sm/scripts/mackplot.q
/usr/lib64/R/library/sm/scripts/mag_dens.q
/usr/lib64/R/library/sm/scripts/mag_scat.q
/usr/lib64/R/library/sm/scripts/mildew.q
/usr/lib64/R/library/sm/scripts/muscle.q
/usr/lib64/R/library/sm/scripts/noeff.q
/usr/lib64/R/library/sm/scripts/nyc.q
/usr/lib64/R/library/sm/scripts/onionbnd.q
/usr/lib64/R/library/sm/scripts/onionplt.q
/usr/lib64/R/library/sm/scripts/rc_alter.q
/usr/lib64/R/library/sm/scripts/rc_boot.q
/usr/lib64/R/library/sm/scripts/rc_plot.q
/usr/lib64/R/library/sm/scripts/rc_vband.q
/usr/lib64/R/library/sm/scripts/sin_cv.q
/usr/lib64/R/library/sm/scripts/sin_prop.q
/usr/lib64/R/library/sm/scripts/smackgam.q
/usr/lib64/R/library/sm/scripts/smackplt.q
/usr/lib64/R/library/sm/scripts/sp_alter.q
/usr/lib64/R/library/sm/scripts/sp_build.q
/usr/lib64/R/library/sm/scripts/sp_comp.q
/usr/lib64/R/library/sm/scripts/sp_comp2.q
/usr/lib64/R/library/sm/scripts/sp_hist.q
/usr/lib64/R/library/sm/scripts/sp_test1.q
/usr/lib64/R/library/sm/scripts/sp_test2.q
/usr/lib64/R/library/sm/scripts/speed.q
/usr/lib64/R/library/sm/scripts/speedvar.q
/usr/lib64/R/library/sm/scripts/stananim.q
/usr/lib64/R/library/sm/scripts/stanplot.q
/usr/lib64/R/library/sm/scripts/te_band.q
/usr/lib64/R/library/sm/scripts/te_hcvsj.q
/usr/lib64/R/library/sm/scripts/te_norm.q
/usr/lib64/R/library/sm/scripts/te_var.q
/usr/lib64/R/library/sm/scripts/trees.q
/usr/lib64/R/library/sm/scripts/trout1.q
/usr/lib64/R/library/sm/scripts/trout2.q
/usr/lib64/R/library/sm/scripts/trw_lf.q
/usr/lib64/R/library/sm/scripts/trw_lfsg.q
/usr/lib64/R/library/sm/scripts/trw_nebd.q
/usr/lib64/R/library/sm/scripts/trw_nesg.q
/usr/lib64/R/library/sm/scripts/trwlband.q
/usr/lib64/R/library/sm/scripts/trwlboot.q
/usr/lib64/R/library/sm/scripts/trwlcmp2.q
/usr/lib64/R/library/sm/scripts/trwlcomp.q
/usr/lib64/R/library/sm/scripts/trwlgam1.q
/usr/lib64/R/library/sm/scripts/trwlgam2.q
/usr/lib64/R/library/sm/scripts/trwlgam3.q
/usr/lib64/R/library/sm/scripts/trwlplot.q
/usr/lib64/R/library/sm/scripts/wormcomp.q
/usr/lib64/R/library/sm/smdata/aircraft.dat
/usr/lib64/R/library/sm/smdata/aircraft.doc
/usr/lib64/R/library/sm/smdata/airpc.dat
/usr/lib64/R/library/sm/smdata/airpc.doc
/usr/lib64/R/library/sm/smdata/birth.dat
/usr/lib64/R/library/sm/smdata/birth.doc
/usr/lib64/R/library/sm/smdata/bissell.dat
/usr/lib64/R/library/sm/smdata/bissell.doc
/usr/lib64/R/library/sm/smdata/bonions.dat
/usr/lib64/R/library/sm/smdata/bonions.doc
/usr/lib64/R/library/sm/smdata/britpts.dat
/usr/lib64/R/library/sm/smdata/citrate.dat
/usr/lib64/R/library/sm/smdata/citrate.doc
/usr/lib64/R/library/sm/smdata/coalash.dat
/usr/lib64/R/library/sm/smdata/coalash.doc
/usr/lib64/R/library/sm/smdata/dogs.dat
/usr/lib64/R/library/sm/smdata/dogs.doc
/usr/lib64/R/library/sm/smdata/follicle.dat
/usr/lib64/R/library/sm/smdata/follicle.doc
/usr/lib64/R/library/sm/smdata/geys3d.dat
/usr/lib64/R/library/sm/smdata/geys3d.doc
/usr/lib64/R/library/sm/smdata/lcancer.dat
/usr/lib64/R/library/sm/smdata/lcancer.doc
/usr/lib64/R/library/sm/smdata/mackerel.dat
/usr/lib64/R/library/sm/smdata/mackerel.doc
/usr/lib64/R/library/sm/smdata/magrem.dat
/usr/lib64/R/library/sm/smdata/magrem.doc
/usr/lib64/R/library/sm/smdata/mildew.dat
/usr/lib64/R/library/sm/smdata/mildew.doc
/usr/lib64/R/library/sm/smdata/muscle.dat
/usr/lib64/R/library/sm/smdata/muscle.doc
/usr/lib64/R/library/sm/smdata/nile.dat
/usr/lib64/R/library/sm/smdata/nile.doc
/usr/lib64/R/library/sm/smdata/phosphat.doc
/usr/lib64/R/library/sm/smdata/poles.dat
/usr/lib64/R/library/sm/smdata/poles.doc
/usr/lib64/R/library/sm/smdata/propsim.dat
/usr/lib64/R/library/sm/smdata/radioc.dat
/usr/lib64/R/library/sm/smdata/radioc.doc
/usr/lib64/R/library/sm/smdata/smacker.dat
/usr/lib64/R/library/sm/smdata/smacker.doc
/usr/lib64/R/library/sm/smdata/stanford.dat
/usr/lib64/R/library/sm/smdata/stanford.doc
/usr/lib64/R/library/sm/smdata/tephra.dat
/usr/lib64/R/library/sm/smdata/tephra.doc
/usr/lib64/R/library/sm/smdata/trawl.dat
/usr/lib64/R/library/sm/smdata/trawl.doc
/usr/lib64/R/library/sm/smdata/trees.dat
/usr/lib64/R/library/sm/smdata/trees.doc
/usr/lib64/R/library/sm/smdata/trout.dat
/usr/lib64/R/library/sm/smdata/trout.doc
/usr/lib64/R/library/sm/smdata/wonions.dat
/usr/lib64/R/library/sm/smdata/wonions.doc
/usr/lib64/R/library/sm/smdata/worm.dat
/usr/lib64/R/library/sm/smdata/worm.doc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/sm/libs/sm.so
/usr/lib64/R/library/sm/libs/sm.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-sm/17e3b0eea99abffe6ac71e65627413236e0b117a
